// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// sampler //
// ------- //

#define sampler_wrap_target 0
#define sampler_wrap 0
#define sampler_pio_version 0

static const uint16_t sampler_program_instructions[] = {
            //     .wrap_target
    0x4008, //  0: in     pins, 8
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program sampler_program = {
    .instructions = sampler_program_instructions,
    .length = 1,
    .origin = -1,
    .pio_version = sampler_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config sampler_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + sampler_wrap_target, offset + sampler_wrap);
    return c;
}
#endif

